version: '3'

services:
   flaskapp:
     build: ./Application
     hostname: flask-host
     depends_on:
       - redis
     networks:
       - redisnet
     ports:
       - "5000:5000"
   redis:
     image: redis
     hostname: redis-server
     networks:
       - redisnet

networks:
    redisnet: